<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>icreditTechCom</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>fd4f477c-f822-4130-9373-f100a4802b9c</testSuiteGuid>
   <testCaseLink>
      <guid>f31c863e-ea75-4b70-862f-4df21a2dd438</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/icreditCom/comLogin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fff157e-5118-4d6e-827f-7c6afc9fb320</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9906e30-bd56-4a9b-8787-6dfae16c8657</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70a87a18-c525-4cbb-9679-f0c511084806</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/icreditCom/applyTech</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>581eb765-fdc5-4940-b0db-19e6563b9359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68d63dd3-039d-46d7-bfda-5b4a4e463059</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53ff02b6-d0a9-4dc2-9176-53f6e63cfa7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c8169f9-81d8-4858-b5e0-9a387ae2573b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fa85aae-0b44-46dc-b690-2fa8d4966562</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdb92fcd-c026-4456-8cf1-eb2d48e27ee6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d778d3e3-b8f6-4347-b9c3-1c5a123a7ed4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27228bd5-0cd1-4a67-96e3-cfc0f5870e32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91b221c2-fa2e-46df-9e61-4bb14cc26121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e06af0e-a5d7-4a70-abd8-bcb652ab5028</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15a57359-d55c-40f8-8aca-a179d092933c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2301bb61-4a41-4a68-8cca-b6bdca04649e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>485661ba-8277-4e33-9858-e28a6dec39a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/icreditCom/withdraw</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ddbc2dcd-3aed-4798-8f2c-c4af4b9bd4a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/icreditCom/reapply</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dd3154f6-bb04-4d25-b403-e716d175fbe9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/icreditBank/bankLogin</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c3ea1967-6e93-44f3-9004-e72e94469b93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/icreditBank/agree</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
