<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirmwith</name>
   <tag></tag>
   <elementGuidId>659bd8c2-e671-43eb-a42c-c21d613b9a41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/button[normalize-space(.)='确定']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
