<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detail</name>
   <tag></tag>
   <elementGuidId>04cff26c-eb18-4c27-a770-b85876f0ec5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/tr/td[normalize-space(.)='审核中']/following-sibling::td/div[normalize-space(.)='查看详情']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
