<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>withdraw</name>
   <tag></tag>
   <elementGuidId>efd87335-d5aa-429f-947b-aaaac8aa7657</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/button[normalize-space(.)='撤回']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
